[package]
name = "day7"
version = "0.1.0"
authors = ["l4p1n <l4p1n@l4p1n.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
